#!/bin/sh

set -e

BIN="$(cd $(dirname "$0"); pwd)"
ROOT="$(cd "$BIN"/..; pwd)"
. "$BIN"/logger.sh
. "$BIN"/ci.sh
verbose_level="$VERBOSE_LEVEL_INFO"

# Check if there in no violation on importing external packages

imports_ok=0
"$BIN"/check_imports || exit 1
imports_ok=1

# Run

cd "$ROOT"
go build
json='verifier.result:{"success":true,"message":"All game passed","steps":10000,"used_switches":0,"score":200000}'

score=$(echo "$json" | jq -r '.score')
steps=$(echo "$json" | jq -r '.steps')
switches=$(echo "$json" | jq -r '.used_switches')
msg=$(echo "$json" | jq -r '.message')

# Report the result

info result "[Score] $score"
info result "[Steps] $steps"
info result "[Used switches] $switches"

[ "$(echo "$json" | jq -r '.success')" = 'true' ] || die "$msg"

info result "$msg"

exit 0
